

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: backend
    volumes:
      - ./backend/.env:/app/.env
      - lancedb_data:/app/output/20240827-100424/artifacts/lancedb
    expose:
      - "8000"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    container_name: frontend
    ports:
      - "80:8501"
    environment:
      - API_URL=http://backend:8000/query
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  lancedb_data:

networks:
  app-network:
