# Dockerfile-backend

# Use the official Python image
FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Copy the backend requirements file
COPY backend/requirements.txt ./requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the backend code
COPY backend/ ./

# Copy the artifacts required by the backend, including lancedb
COPY output/20240827-100424/artifacts/ ./output/20240827-100424/artifacts/

# Copy the .env file
COPY backend/.env ./.env

# Expose the backend port
EXPOSE 8000

# Add entrypoint script to adjust permissions
COPY ./backend/backend_entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

# Set the entrypoint
ENTRYPOINT ["/app/entrypoint.sh"]

# Run the backend application
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
