# Dockerfile-frontend

# Use the official Python image
FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Copy the frontend requirements file
COPY frontend/requirements.txt ./requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the frontend code
COPY frontend/ ./

# Expose the frontend port
EXPOSE 8501

# Run the Streamlit app
CMD ["streamlit", "run", "main.py", "--server.port=8501", "--server.address=0.0.0.0"]
